#!/usr/bin/env python3
import requests
import discord
from discord import Webhook, RequestsWebhookAdapter, File
 
# Create webhook
webhook = Webhook.partial(WEBHOOK_ID, WEBHOOK_TOKEN,\
 adapter=RequestsWebhookAdapter())
 
# Dongle
webhook.send(USER_NAME + "NONE OF THAT.")
